### ISSUE TITLE
InlineDatePicker: after selecting a day, moving to next month updates month description but does not update the calendar

### ISSUE THREAD

**Issue by dicorato** [FlowingCode/YearMonthCalendarAddon#81] opened 2024-08-29 11:05 UTC
### Describe the bug

Using InlineDatePicker, selecting one of the days displayed and then moving to next month is not updating the calendar showing the days of the next month, just updates the month description. You have to click again to show the correct month days.

### Minimal reproducible example

```
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.notification.Notification;
import java.util.Objects;

public class InlineDatePickerDemo extends Div {

  public InlineDatePickerDemo() {

    InlineDatePicker field = new InlineDatePicker();

    field.addValueChangeListener(ev->{
      Notification.show(Objects.toString(ev.getValue()));
    });
    add(field);
  }

}
```

### Add-on Version

4.2.2-SNAPSHOT

### Vaadin Version

24

### Additional information

You can experience the bug on the official demo site: https://addonsv24.flowingcode.com/year-month-calendar/inline-date-picker

**Comment by javier-godoy** [comment] 2024-08-29 13:51
Hello. Did I get the reproduction steps right? The feature seems to work in the demo site. (In case it matters, I'm using Chrome 128).
![81](https://github.com/user-attachments/assets/ba51dc4b-b94d-40e8-8bfd-b02786593e7a)

**Comment by dicorato** [comment] 2024-08-29 14:14
Hello Javier, yes, the steps are right. I can experience the problem on the demo site using both Firefox 129 and Chrome 128. I just found another strange behaviour linked to the same problem. What are you using to create those GIFs? So I show you.
Thanks

**Comment by javier-godoy** [comment] 2024-08-30 10:22
Hello. I create the GIFs with [LiceCap](https://github.com/justinfrankel/licecap). Windows / macOS installers are available from the website linked from their repository.

**Comment by javier-godoy** [comment] 2024-10-14 13:57
Since we haven't received any further updates, we're closing this issue. Feel free to reopen or create a new one if you need more help.

**Closed by javier-godoy** 2024-10-14 13:57 UTC
Labels: question
